import {
    VerticalBox,
    HorizontalBox,
    ComboBox,
    ScrollView,
    GroupBox,
} from "std-widgets.slint";
import { Theme, Layout } from "../theme.slint";
import { ArchiveLibraryItem, CrudListItem } from "../models.slint";
import { ThemedButton } from "../dialogs.slint";
import { CrudList } from "../crud-list.slint";

export component SettingsPage inherits VerticalBox {
    in property <[ArchiveLibraryItem]> archive_library_items: [];
    in property <[CrudListItem]> archive_library_crud_items: [];
    in-out property <int> selected_archive: 0;
    in-out property <int> selected_language: 0; // 0: Chinese, 1: English

    callback add_archive_library();
    callback remove_archive_library();
    callback rename_archive_library(int, string);
    callback apply_settings();
    callback cancel_settings();
    alignment: start;
    padding: Layout.standard_padding;
    spacing: Layout.standard_spacing;
    vertical-stretch: 1;
    GroupBox {
        title: @tr("label_language");
        HorizontalBox {
            padding: Layout.standard_padding;
            spacing: Layout.standard_spacing;
            height: Layout.row_height;
            Text {
                text: @tr("label_language");
                width: 120px;
                vertical-alignment: center;
            }

            ComboBox {
                model: ["中文 (Chinese)", "English (英文)"];
                current-index <=> root.selected_language;
                horizontal-stretch: 1;
            }
        }
    }

    GroupBox {
        height: 400px;
        CrudList {
            vertical-stretch: 1;
            title: @tr("label_archive_libraries");
            items: root.archive_library_crud_items;
            active-index <=> root.selected_archive;
            show-add-button: true;
            show-rename-menu: true;
            add-clicked => {
                root.add_archive_library();
            }
            item-clicked(index, ctrl, shift) => {
                root.selected_archive = index;
            }
            rename-clicked(index, old_name) => {
                root.rename_archive_library(index, old_name);
            }
            delete-clicked => {
                root.remove_archive_library();
            }
        }
    }

    HorizontalBox {
        alignment: end;
        spacing: Layout.standard_spacing;
        ThemedButton {
            text: @tr("btn_cancel");
            is_primary: false;
            clicked => {
                root.cancel_settings();
            }
        }

        ThemedButton {
            text: @tr("btn_apply");
            is_primary: true;
            clicked => {
                root.apply_settings();
            }
        }
    }
}
