export component TooltipLayer inherits Rectangle {
    in property <bool> is_hovered: false;
    in property <length> offset_y: 0px;
    in property <length> offset_x: 55px;
    in property <string> text: "";
    in property <length> tooltip_width: 100px;

    x: offset_x;
    y: offset_y;
    width: tooltip_width;
    height: 32px;
    visible: is_hovered;
    background: #333;
    border-radius: 4px;
    border-width: 1px;
    border-color: #555;

    Text {
        x: 0px;
        y: 0px;
        width: 100%;
        height: 100%;
        text: root.text;
        font-size: 12px;
        color: white;
        horizontal-alignment: center;
        vertical-alignment: center;
    }
}